#.travis.yml

language: node_js
node_js:
  - "7"
dist: trusty


branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

 notifications:
    slack: houseskipper:smfTiIqJXd6xCpCqeMBCqXeY
